name: motor_home
description: This project focuses on the development of an innovative
  application to monitor the sensors of a motor home.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  background_fetch: ^1.2.1
  bloc: ^8.1.2
  bloc_concurrency: ^0.2.2
  connectivity_plus: ^5.0.1
  dartz: ^0.10.1
  dio: ^5.3.3
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_blue_plus: ^1.16.2
  flutter_bluetooth_serial: ^0.4.0
  flutter_dotenv: ^5.1.0
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.7
  font_awesome_flutter: ^10.5.0
  freezed_annotation: ^2.4.1
  get_it: ^7.6.4
  hydrated_bloc: ^9.1.2
  intl: ^0.18.0
  json_annotation: ^4.8.1
  mqtt5_client: ^4.0.3
  path_provider: ^2.1.1
  permission_handler: ^11.0.1
  shared_preferences: ^2.2.1
  showcaseview: ^2.0.3

dev_dependencies:
  bloc_test: ^9.1.4
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter
  freezed: ^2.4.5
  json_serializable: ^6.7.1
  mocktail: ^1.0.0
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - .env
    - assets/images/
    - assets/images/svg/
    - assets/images/png/
    - assets/images/gif/
    - assets/icons/
    - assets/fonts/
